// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantsWatering.Server.Db;

#nullable disable

namespace PlantsWatering.Server.Migrations
{
    [DbContext(typeof(PlantsDbContext))]
    [Migration("20220131080414_AddWateringSchedule")]
    partial class AddWateringSchedule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("PlantsWatering.Server.Db.Models.PlantDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommunicationChannelId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("PlantsWatering.Server.Db.Models.PlantDbo", b =>
                {
                    b.OwnsOne("PlantsWatering.Server.Db.Models.WateringScheduleDbo", "WateringSchedule", b1 =>
                        {
                            b1.Property<int>("PlantDboId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Rate")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("WateringHour")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("WateringMinute")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlantDboId");

                            b1.ToTable("Plants");

                            b1.WithOwner()
                                .HasForeignKey("PlantDboId");
                        });

                    b.Navigation("WateringSchedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
